from . import views
from django.urls import include, path

from main.views import (
    account_profile,
    create_portfolio_item,
    create_project,
    create_project_ajax,
    chat_message_action,
    chat_messages,
    community_chat,
    delete_portfolio_item,
    delete_project,
    get_portfolio_json,
    get_portfolio_xml,
    get_projects_json,
    get_projects_xml,
    login_user,
    logout_user,
    project_comment_action,
    project_comments,
    public_member_profile,
    register,
    show_experience,
    show_main,
    show_portfolio,
    show_portfolio_deserialized,
    show_projects,
    show_projects_deserialized,
    toggle_star,
    update_portfolio_item,
    update_project,
    update_project_order,
)


app_name = "main"

urlpatterns = [
    path("", show_main, name="show_main"),
    path("experience/", show_experience, name="show_experience"),
    path("portfolio/", show_portfolio, name="show_portfolio"),
    path("projects/", show_projects, name="show_projects"),
    path("portfolio/add/", create_portfolio_item, name="create_portfolio_item"),
    path("projects/add/", create_project, name="create_project"),
    path("portfolio/<uuid:portfolio_id>/update/", update_portfolio_item, name="update_portfolio_item"),
    path("projects/<uuid:project_id>/update/", update_project, name="update_project"),
    path("portfolio/<uuid:portfolio_id>/delete/", delete_portfolio_item, name="delete_portfolio_item"),
    path("projects/<uuid:project_id>/delete/", delete_project, name="delete_project"),
    path("portfolio/deserialized/", show_portfolio_deserialized, name="show_portfolio_deserialized"),
    path("projects/deserialized/", show_projects_deserialized, name="show_projects_deserialized"),
    path("api/portfolio/", get_portfolio_json, name="get_portfolio_json"),
    path("api/portfolio/xml/", get_portfolio_xml, name="get_portfolio_xml"),
    path("api/projects/", get_projects_json, name="get_projects_json"),
    path("api/projects/<uuid:project_id>/comments/", project_comments, name="project_comments"),
    path("api/project-comments/<int:comment_id>/", project_comment_action, name="project_comment_action"),
    path("api/projects/xml/", get_projects_xml, name="get_projects_xml"),
    path("register/", register, name="register"),
    path("login/", login_user, name="login"),
    path("account/profile/", account_profile, name="account_profile"),
    path("members/<str:username>/", public_member_profile, name="public_member_profile"),
    path("community/chat/", community_chat, name="community_chat"),
    path("api/community/messages/", chat_messages, name="chat_messages"),
    path("api/community/messages/<int:message_id>/", chat_message_action, name="chat_message_action"),
    path("logout/", logout_user, name="logout"),
    path("projects/<uuid:project_id>/star/", toggle_star, name="toggle_star"),
    path("projects/reorder/", update_project_order, name="update_project_order"),
    path("projects/add-ajax/", create_project_ajax, name="create_project_ajax"),
    path("contacts/", views.contact_list, name="contact_list"),
    path("contacts/add/", views.contact_add, name="contact_add"),
    path("contacts/search/", views.contact_search, name="contact_search"),
    path("contacts/<int:pk>/delete/", views.contact_delete, name="contact_delete"),
    path("contacts/<int:pk>/edit/", views.contact_edit, name="contact_edit"),
    path("contacts/<int:pk>/row/", views.contact_row, name="contact_row"),
    path("contacts/<int:pk>/update/", views.contact_update, name="contact_update"),
]
