# Generated by Django 5.2.17 on 2026-09-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_portfolioitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='project_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='project_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='tech_stack',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
