# Generated by Django 5.2.17 on 2026-09-17 05:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_portfolioitem_project_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('estimated_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_featured', models.BooleanField(default=False)),
                ('submission_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
