# Generated by Django 5.2.17 on 2026-10-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_chatmessage_reply_to_projectcomment_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconnection',
            name='platform',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('roblox', 'Roblox'), ('spotify', 'Spotify'), ('twitch', 'Twitch'), ('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('website', 'Website'), ('other', 'Other')], max_length=50),
        ),
    ]
